feat: 2022 Frosh Week landing page (timer) and info page
CSSS/csss-site pull request #454
Opened 2022-08-09 05:15 UTC by Liversticks

Create Frosh 2022 pages.

- [ x ] fix link on [csss-site/src/events/frosh/templates/frosh/frosh_week.html](https://github.com/CSSS/csss-site/blob/master/csss-site/src/events/frosh/templates/frosh/frosh_week.html) to point to new frosh page instead of under construction page
- [ x ] Follow the example of the previous years and add the necessary URL patterns under [csss-site/src/events/frosh/urls.py](https://github.com/CSSS/csss-site/blob/master/csss-site/src/events/frosh/urls.py). You will need to add a url pattern for each new webpage you intend to make (with an extra "treat" this year)
- [ x ] Create a new views file for the frosh year under [csss-site/src/events/frosh/views](https://github.com/CSSS/csss-site/blob/master/csss-site/src/events/frosh/views). You can take a look at the views from previous years to see how to populate it.
- [ x ] You will also need to actually put the static files on the repo, they will need to go under a new folder in [csss-site/src/events/frosh/static/frosh_static](https://github.com/CSSS/csss-site/blob/master/csss-site/src/events/frosh/static/frosh_static). This year, there are 4 folders:
    - css: Main Frosh site CSS (Normalize + custom (includes a subset of Bootstrap)
    - favicon: Assets for favicons on different devices
    - images: Logos for Frosh and sponsors + banner
    - js: Main Frosh site JS (subset of Bootstrap)
    - landing_page: Copy of existing landing page assets with the start date adjusted to be September 12, 2022, 21:30 GMT (13:30 PDT)
- [ x ] The html page[s] that you intend to make will go under their appropriate folder name in [csss-site/src/events/frosh/templates/frosh](https://github.com/CSSS/csss-site/blob/master/csss-site/src/events/frosh/templates/frosh). 2 thing to keep in mind about the html pages. The page was generated from [my personal repo](https://github.com/Liversticks/frosh-2022-website) using Eleventy.js, then I went and substituted static links for Django.

2022-08-11 00:44 UTC, modernNeo commented
you do realize in the sign up form
> The Simon Fraser University Computing Science Student Society (CSSS) presents Frosh Week 2022! Join us for our annual Welcome Week event dedicated to you, the first years of SFU Computing Science!

> Learn more about our events here at our website at: [https://sfucsss.org/events/frosh/2022/frosh](https://sfucsss.org/events/frosh/2021/frosh) 
Stay up to date with event news by joining our Discord Server at https://discord.gg/sfucsss.
For any questions, you can email [csss-froshchair@sfu.ca](mailto:csss-froshchair@sfu.ca)

The link is for 2021

2022-08-11 01:10 UTC, modernNeo requested changes
what is
 - csss-site/src/events/frosh/static/frosh_static/2022/favicon/browserconfig.xml
 - csss-site/src/events/frosh/static/frosh_static/2022/favicon/site.webmanifest
?

Did you forget to link to the favicon from the https://dev.sfucsss.org/PR-454/events/frosh/2022 ?

you sure 
 - csss-site/src/events/frosh/static/frosh_static/2022/favicon/favicon.ico
 - csss-site/src/events/frosh/static/frosh_static/2022/favicon/android-chrome-192x192.png
 - csss-site/src/events/frosh/static/frosh_static/2022/favicon/android-chrome-512x512.png

are being used?

2022-08-12 03:51 UTC, Liversticks commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
It's not Frosh Week without a little bit of trolling.

Regarding the favicons, they are that way to be more accessible on mobile. The favicons are referenced via the XML file and the web manifest.

2022-08-12 04:00 UTC, Liversticks commented
Frosh Committee is meeting tomorrow, will try and get final rooms for Info Session, Pac Macro etc. by Friday night.

2022-08-12 04:04 UTC, sahsan199 commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
I like the trolling. I think it's a nice addition. Let's go ahead and add it

2022-08-12 04:08 UTC, modernNeo commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
> Regarding the favicons, they are that way to be more accessible on mobile. The favicons are referenced via the XML file and the web manifest.

@Liversticks 
Are you sure they are being used though? I couldn't detect them being used when toggling mobile view on my browser.

2022-08-12 04:09 UTC, modernNeo commented
> Frosh Committee is meeting tomorrow, will try and get final rooms for Info Session, Pac Macro etc. by Friday night.

@Liversticks is this relevant to me?

2022-08-12 04:52 UTC, modernNeo commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
@Liversticks as you can see from my screenshots. favicon.ico is not accessible when accessing the landing page from a desktop view
![landing_page_from_desktop](https://user-images.githubusercontent.com/14242088/184287101-305edebe-1542-4db2-b7a1-2ce1631aaf72.png)

Furthmore,
the favicons specified in `csss-site/src/events/frosh/static/frosh_static/2022/favicon/site.webmanifest` don't seem to be loaded when accessing the main page, as you can see from these screenshots
![main_page_from_chrome_mobile](https://user-images.githubusercontent.com/14242088/184287200-915730df-ec34-46e3-8ab6-2ace1bbc268d.png)
![main_page_from_desktop](https://user-images.githubusercontent.com/14242088/184287203-01282d51-abb2-4aba-a76e-11bd19298a8f.png)
![main_page_from_mobile](https://user-images.githubusercontent.com/14242088/184287206-626a0e98-a42b-4aeb-ab2d-441e1aab3eed.png)

2022-08-12 04:58 UTC, Liversticks commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
According to this source (https://realfavicongenerator.net/blog/new-favicon-package-less-is-more/) (also where I generated the assets), the 192x192 and 512x512 PNGs are deprecated so I removed them (in next commit). I think we can keep the favicon though.

2022-08-12 05:00 UTC, Liversticks commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
Hmm, the favicon might not be located in the root. Since we're not going to put it in the site root, I will also remove it.

2022-08-12 05:00 UTC, Liversticks commented
> > Frosh Committee is meeting tomorrow, will try and get final rooms for Info Session, Pac Macro etc. by Friday night.
> 
> @Liversticks is this relevant to me?

it means I'll likely have another PR open next week.

2022-08-12 05:03 UTC, Liversticks commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
Point is, most of these files are intended to offer favicon support over a reasonable amount of platforms. I understand the commitment to reduce bloat/unused files, but given we have so much un-minified JS (especially multiple years' sites reusing similar static assets), I don't think these favicons will hurt the bottom line too much.

2022-08-12 05:07 UTC, modernNeo commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
@Liversticks 
> Point is, most of these files are intended to offer favicon support over a reasonable amount of platforms. I understand the commitment to reduce bloat/unused files, but given we have so much un-minified JS (especially multiple years' sites reusing similar static assets), I don't think these favicons will hurt the bottom line too much.

I personally went through all the static files a year or 2 ago myself to ensure they are all being used so you can't claim that the repos hold JS files for frosh week that are not necessary.

> I don't think these favicons will hurt the bottom line too much.

I am not gonna approve a PR that is attempting to merge files that are not being used. There is no sense in that.

If the favicons you have included are being used, please feel free to let me know how to duplicate the instance in which they are being used.

2022-08-12 05:18 UTC, Liversticks commented on csss-site/src/events/frosh/urls.py
> +    url(r'^2022/secret$', frosh2022.secret, name="Not A Secret"),
Makes sense. I don't have a way to emulate all the devices that could hypothetically use the favicons so I just removed all of them except the 16x16, 32x32, and apple-touch-icon ones in the most recent commit.

2022-08-13 02:04 UTC, Liversticks reviewed
Removed all unused favicons. There are currently 3 (16x16, 32x32, and apple-touch-icon) which are referenced in both new HTML pages.

2022-08-13 02:06 UTC, Liversticks reviewed
This is the initial version that contains several unused favicons. Please disregard this revision in favor of the most recent one.

2022-08-13 12:18 UTC, modernNeo requested changes
please address these errors: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev.sfucsss.org%2FPR-454%2Fevents%2Ffrosh%2F2022%2Ffrosh

2022-08-13 23:25 UTC, Liversticks commented
> please address these errors: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev.sfucsss.org%2FPR-454%2Fevents%2Ffrosh%2F2022%2Ffrosh

Addressed in latest commit (https://github.com/CSSS/csss-site/pull/454/commits/8fe74f3e5aff76d86eff467aa423d20f14df8472)

2022-08-15 04:47 UTC, modernNeo commented
> you do realize in the sign up form
> 
> > The Simon Fraser University Computing Science Student Society (CSSS) presents Frosh Week 2022! Join us for our annual Welcome Week event dedicated to you, the first years of SFU Computing Science!
> 
> > Learn more about our events here at our website at: [https://sfucsss.org/events/frosh/2022/frosh](https://sfucsss.org/events/frosh/2021/frosh)
> > Stay up to date with event news by joining our Discord Server at https://discord.gg/sfucsss.
> > For any questions, you can email [csss-froshchair@sfu.ca](mailto:csss-froshchair@sfu.ca)
> 
> The link is for 2021

@Liversticks you never addressed this.

2022-08-15 07:16 UTC, Liversticks commented
> > you do realize in the sign up form
> > > The Simon Fraser University Computing Science Student Society (CSSS) presents Frosh Week 2022! Join us for our annual Welcome Week event dedicated to you, the first years of SFU Computing Science!
> > 
> > 
> > > Learn more about our events here at our website at: [https://sfucsss.org/events/frosh/2022/frosh](https://sfucsss.org/events/frosh/2021/frosh)
> > > Stay up to date with event news by joining our Discord Server at https://discord.gg/sfucsss.
> > > For any questions, you can email [csss-froshchair@sfu.ca](mailto:csss-froshchair@sfu.ca)
> > 
> > 
> > The link is for 2021
> 
> @Liversticks you never addressed this.

@modernNeo 
Thank you for pointing this out, I previously made some changes to the form but I didn't adjust the shortened URL. That has been addressed in the latest commit.

2022-08-16 02:33 UTC, merged