Tech fair 2023 Finalizing
CSSS/csss-site pull request #627
Opened 2023-11-20 01:37 UTC by EarthenSky

Now that tech fair is over, the site's wording has to be modified. Also, a few companies that attended were not added to the site, so I've added those.

In addition, as requested by our VP Valerie, I've added a kind of meta-techfair page, called the "Timeline". Will check in with her about naming, but this is a directory of all the tech fairs.

2023-11-20 03:43 UTC, EarthenSky commented
CI has the same issue as before, where it's failing accidentally due to some kind of race condition (I suspect). However, the pages themselves should be fine.

2023-11-20 05:16 UTC, modernNeo commented
build

2023-11-20 05:16 UTC, modernNeo commented
> CI has the same issue as before, where it's failing accidentally due to some kind of race condition (I suspect).

I really gotta spend time on figuring that bug out 😞 . guess I can do that now that my work on wall_e is pretty much done.

Such an annoying bug

2023-11-20 05:48 UTC, modernNeo requested changes
please address above issues and fix https://dev.sfucsss.org/PR-627/events/tech_fair/2022/main which I think this PR broke. [run it with the network tab open in the developer console to see what I mean]

2023-11-20 05:48 UTC, modernNeo commented on csss-site/src/csss/templates/csss/header.html
> +							<a href="{{URL_ROOT}}events/tech_fair/timeline" class="navbar-item">Tech Fair</a>
should really be renamed "Tech Fairs" then

2023-11-20 05:48 UTC, modernNeo commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/fonts/DarumadropOne-Regular.ttf
where is this used?

2023-11-20 05:48 UTC, modernNeo commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/fonts/NotoSansGeorgian-Bold.ttf
where is this used?

2023-11-20 05:48 UTC, modernNeo commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/fonts/NotoSansGeorgian-Regular.ttf
where is this used?

2023-11-20 05:48 UTC, modernNeo commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/images/2023-1.jpg
where is this used?

2023-11-20 07:01 UTC, EarthenSky commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/fonts/DarumadropOne-Regular.ttf
In the title of the tech fair page

2023-11-20 07:02 UTC, EarthenSky commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/fonts/NotoSansGeorgian-Bold.ttf
In the subtitles in the tech fair page

2023-11-20 07:02 UTC, EarthenSky commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/fonts/NotoSansGeorgian-Regular.ttf
for body text in the tech fair page

2023-11-20 09:59 UTC, modernNeo commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/fonts/DarumadropOne-Regular.ttf
which file? I am doing a ctrl+f for `DarumadropOne-Regular.ttf` and I don't see it.

2023-11-20 10:02 UTC, EarthenSky commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/images/2023-1.jpg
It's not used in this pr, but I was asked to add even more images, which I'll be doing eventually

2023-11-20 10:03 UTC, modernNeo commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/images/2023-1.jpg
then can you remove it and add it in the PR where it will be used?

2023-11-21 05:49 UTC, EarthenSky commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/fonts/DarumadropOne-Regular.ttf
in `.../static/tech_fair/timeline/css/main.css` line 56:
```css
@font-face {
    font-family: "darumadropOne";
    src: url("../fonts/DarumadropOne-Regular.ttf");
}
```

The fonts were added in a previous PR. This PR is only moving them.

2023-11-21 05:50 UTC, EarthenSky commented on csss-site/src/events/tech_fair/static/tech_fair/timeline/images/2023-1.jpg
sure thing!

2023-11-21 06:07 UTC, EarthenSky commented
The w3c validation checker is failing because the https://dev.sfucsss.org/PR-627/events/tech_fair/2023 is giving "Internal Server Error"

2023-11-21 16:50 UTC, modernNeo commented
build

2023-11-21 17:06 UTC, modernNeo commented
@EarthenSky look again

2023-11-22 05:42 UTC, EarthenSky commented
> @EarthenSky look again

Praise, it works! tysm

2023-11-22 07:46 UTC, EarthenSky commented
build

2023-11-22 08:00 UTC, EarthenSky commented
:0 magic

2023-11-24 08:40 UTC, modernNeo commented
please rebase this off of master

you can do that using `git pull --rebase upstream master` [or whatever name you have set for https://github.com/CSSS/csss-site.git in youre repo]

2023-11-24 08:52 UTC, modernNeo commented
please do
```bash
git remote add upstream https://github.com/CSSS/csss-site.git
git fetch upstream
git pull --rebase upstream master
git push origin tech-fair-2023-finalizing -f
```

2023-11-24 08:54 UTC, modernNeo requested changes
please rebase off of master with the following
```bash
git remote add upstream https://github.com/CSSS/csss-site.git
git fetch upstream
git pull --rebase upstream master
git push origin tech-fair-2023-finalizing -f
```

2023-11-24 08:54 UTC, modernNeo commented
# **don't do a pull before following the above rebase commands**

2023-11-26 07:04 UTC, merged